version: 2

sources:

  - name: greenery # name of the source 
    schema: public # this is the schema our raw data lives in
    database: dbt # this is the name of our database


    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
     
      - name: users 
        description: >
          Information about each user

      - name: addresses 
        description: >
          Address Information

      - name: events 
        description: >
            Information on events

      - name: orders 
        description: >
          Information on order

      - name: order_items 
        description: >
          Information in items ordered

      - name: products 
        description: >
          Product info

      - name: promos 
        description: >
          Promo info

